### ISSUE TITLE
kali运行报错

### ISSUE THREAD

**Issue by ggwshk** [bytedance/appshark#10]
环境：
1. 刚更新好的Kali
2. Java11.0.15
3. gradle7.0

报错如下：
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
2022-09-14 12:31:20:117:welcome to appshark 0.1
2022-09-14 12:31:20:139:started...
java.lang.RuntimeException: Error when looking for manifest in apk: java.util.zip.ZipException: zip END header not found
	at soot.Scene.getTargetSDKVersion(Scene.java:547)
	at soot.Scene.getAndroidAPIVersion(Scene.java:461)
	at soot.Scene.getAndroidJarPath(Scene.java:420)
	at net.bytedance.security.app.AnalyzeStepByStep.initSoot(AnalyzeStepByStep.kt:131)
	at net.bytedance.security.app.StaticAnalyzeMain.startAnalyze(StaticAnalyzeMain.kt:43)
	at net.bytedance.security.app.StaticAnalyzeMainKt$main$2.invokeSuspend(StaticAnalyzeMain.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.bytedance.security.app.StaticAnalyzeMainKt.main(StaticAnalyzeMain.kt:99)
	at net.bytedance.security.app.KotlinEntry$Companion.callMain(KotlinEntry.kt:24)
	at net.bytedance.security.app.KotlinEntry.callMain(KotlinEntry.kt)
	at net.bytedance.security.app.JavaEntry.main(JavaEntry.java:6)

![image](https://user-images.githubusercontent.com/48978821/190060528-f4d9ae3c-7fa9-4afb-b31f-3767baad2397.png)

**Comment by nkbai** [comment]
看样子是，提供了无效的apk文件，目前我们仅支持扫描apk文件
