### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by LiHongHui6** [bytedance/appshark#32]
![image](https://user-images.githubusercontent.com/23067634/215416424-f3636fea-9db3-4fb4-bc0a-19bc7c352c70.png)

**Comment by nkbai** [comment]
是不是config.json5中，rules参数最后多了一个逗号？ 麻烦检查一下。

**Comment by GHpeter** [comment]
java.lang.RuntimeException: file '?E:/ASCode/appshark-main/jiance.apk' does not exist!
        at soot.Scene.getAndroidAPIVersion(Scene.java:450)
        at soot.Scene.getAndroidJarPath(Scene.java:420)
        at net.bytedance.security.app.AnalyzeStepByStep.initSoot(AnalyzeStepByStep.kt:131)
        at net.bytedance.security.app.StaticAnalyzeMain.startAnalyze(StaticAnalyzeMain.kt:43)
        at net.bytedance.security.app.StaticAnalyzeMainKt$main$2.invokeSuspend(StaticAnalyzeMain.kt:99)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at net.bytedance.security.app.StaticAnalyzeMainKt.main(StaticAnalyzeMain.kt:99)
        at net.bytedance.security.app.KotlinEntry$Companion.callMain(KotlinEntry.kt:24)
        at net.bytedance.security.app.KotlinEntry.callMain(KotlinEntry.kt)
        at net.bytedance.security.app.JavaEntry.main(JavaEntry.java:6)

提示文件路径不存在，不管路径是否是正（反）斜杠
